### ISSUE TITLE
minor aesthetic adjustments

### ISSUE THREAD

**Issue by tgerke** [tgerke/episnpR#1]
- [x] change main title from Linkage Disequilibrium to episnpR
- [x] change SNP List to Query SNPs
- [x] delete "Fill in SN" and change "SNPs" to "Enter SNP rsIDs" (separated by commas?)
- [x] put the "Show Table" button underneath that text box, but change its name to "Perform query"
- [x] can remove the file parameters options altogether, since we're telling the user to enter them as one rsID per line
- [x] on App details, can create a list "Development Team" and put sections "Programming: Jordan Creed, Travis Gerke" and "Scientific input: Alvaro Monteiro"

**Comment by jhcreed** [comment]
We could remove the file parameters options, but then we would need to specify that they upload a specific type of file (e.g. must be text file, without headers, one snp per line no sep).

**Comment by tgerke** [comment]
yes, let's do that. I've seen it done several times on Broad apps, for example, and I don't think it overly burdens the user
