### ISSUE TITLE
generate visual without clicking TAD link first

### ISSUE THREAD

**Issue by tgerke** [tgerke/episnpR#10]
one way to do this would be to implement a grayed-out section in the visual saying "TAD boundaries not yet calculated" or similar in the TAD row 

although: I might be more in favor of just calculating the TAD boundary up front, with a toggle box to turn that option off if the user wishes. The benefit of this would be that you could use a consistent boundary (max of LD/TAD) across all resources. If it takes a few seconds, just put the hourglass -- I haven't yet had a query take >15 seconds which seems ok

**Comment by jhcreed** [comment]
It is now set up for a consistent LD/TAD boundary with the program just running the TAD query upfront. I did it two different ways, so that is why there are two commits that are basically the same thing in the comments
